# Generated by Django 6.0.3 on 2026-03-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='c0000', max_length=20, primary_key=True, serialize=False),
        ),
    ]
