# Generated by Django 6.0.3 on 2026-03-10 23:30

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=django_enum.fields.EnumCharField(choices=[('V0', 'VIP'), ('V1', 'regular')], max_length=2, null=True),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['V0', 'V1']), ('tipo__isnull', True), _connector='OR'), name='clientes_Cliente_tipo_TextEnum'),
        ),
    ]
